package jsymbolic2.ngrams;

import java.util.HashMap;
import java.util.LinkedList;

/**
 * This object aggregates two-dimensional n-grams generated by the NGramGenerator object and returns useful 
 * information for use by feature calculators. Each instance of this object is instantiated with a list of 
 * two-dimensional n-grams. 
 * 
 * This object inherits the fields linking unique identifiers and their respective frequencies, though it 
 * should be noted that the function of these fields is different when aggregating two-dimensional n-grams 
 * because two-dimensional n-grams have a secondary identifier, and consequently a joint identifier composed 
 * of the n-gram's (primary) identifier and its secondary identifier. For example, this object's 
 * n_gram_by_unique_id_to_frequency_map field does not map all n-grams in the list of n-grams passed to this 
 * object, but only the n-grams with unique primary identifiers (two two-dimensional n-grams may share the 
 * same secondary identifier). To facilitate analysis of the n-grams by secondary or joint identifier only, 
 * this object creates the same structures (a hash map and two corresponding arrays) for them at 
 * instantiation.
 * 
 * @author radamian
 */
public class TwoDimensionalNGramAggregate 
		extends NGramAggregate
{
	/**
	 * A HashMap linking a two-dimensional n-gram's secondary string identifier with the normalized frequency 
	 * at which n-grams with that secondary string identifier occur among n-grams from this object's list of 
	 * n-grams that have a unique secondary identifier.
	 */
	private HashMap<String, Double> secondary_string_id_to_frequency_map;
	
	/**
	 * An array of two-dimensional n-grams having a unique secondary identifier among this object's list of 
	 * n-grams. The length of this array is the same of the length of frequencies_by_unique_secondary_id. The 
	 * n-gram at each index occurs among n-grams from this object's list of n-grams that have a unique 
	 * secondary identifier at the frequency found at the same index in frequencies_by_unique_secondary_id.
	 */
	private TwoDimensionalNGram[] n_grams_by_unique_secondary_id;
	
	/**
	 * A normalized histogram containing the frequencies at which each n-gram having a unique secondary 
	 * identifier occurs among n-grams from this object's list of n-grams that have a unique secondary 
	 * identifier. The length of this array is the same of the length of n_grams_by_unique_secondary_id.
	 */
	private double[] frequencies_by_unique_secondary_id;
	
	/**
	 * A HashMap linking a two-dimensional n-gram's joint string identifier with the normalized frequency at 
	 * which n-grams with that joint string identifier occur among n-grams from this object's list of n-grams 
	 * that have a unique joint identifier.
	 */
	private HashMap<String, Double> joint_string_id_to_frequency_map;
	
	/**
	 * An array of n-grams having a unique joint identifier among this object's list of n-grams. The length of 
	 * this array is the same of the length of frequencies_by_unique_joint_id. The n-gram at each index occurs 
	 * among n-grams from this object's list of n-grams that have a unique joint identifier at the frequency 
	 * found at the same index in frequencies_by_unique_joint_id.
	 */
	private TwoDimensionalNGram[] n_grams_by_unique_joint_id;
	
	/**
	 * A normalized histogram containing the frequencies at which each n-gram having a unique joint 
	 * identifier occurs among n-grams from this object's list of n-grams that have a unique joint 
	 * identifier. The length of this array is the same as the length of n_grams_by_unique_joint_id.
	 */
	private double[] frequencies_by_unique_joint_id;
	
	
	/* CONSTRUCTOR ******************************************************************************************/

	
	/**
	 * Create an aggregate of the given list of n-grams.
	 * 
	 * @param	n_gram_list		The list of n-grams that this object aggregates.
	 */
	public TwoDimensionalNGramAggregate(LinkedList<NGram> n_gram_list)
	{
		super(n_gram_list);
		
		secondary_string_id_to_frequency_map = new HashMap<>();
		joint_string_id_to_frequency_map = new HashMap<>();
		
		LinkedList<TwoDimensionalNGram> n_grams_by_unique_secondary_id_ll = new LinkedList<>();
		LinkedList<TwoDimensionalNGram> n_grams_by_unique_joint_id_ll = new LinkedList<>();
		
		for (NGram n_gram: n_grams)
		{
			String secondary_string_id = ((TwoDimensionalNGram) n_gram).getSecondaryStringIdentifier();
			String joint_string_id = ((TwoDimensionalNGram) n_gram).getJointStringIdentifier();
			
			// Verify whether an n-gram having the same secondary identifier has been encountered yet
			if (secondary_string_id_to_frequency_map.get(secondary_string_id) == null)
			{
				secondary_string_id_to_frequency_map.put(secondary_string_id, 1.0);
				n_grams_by_unique_secondary_id_ll.add((TwoDimensionalNGram) n_gram);
			}
			else
			{
				double old_frequency = secondary_string_id_to_frequency_map.get(secondary_string_id);
				secondary_string_id_to_frequency_map.put(secondary_string_id, old_frequency + 1);
			}
			
			// Verify whether an n-gram having the same joint identifier has been encountered yet
			if (joint_string_id_to_frequency_map.get(joint_string_id) == null)
			{
				joint_string_id_to_frequency_map.put(joint_string_id, 1.0);
				n_grams_by_unique_joint_id_ll.add((TwoDimensionalNGram) n_gram);
			}
			else
			{
				double old_frequency = joint_string_id_to_frequency_map.get(joint_string_id);
				joint_string_id_to_frequency_map.put(joint_string_id, old_frequency + 1);
			}
		}
		
		n_grams_by_unique_secondary_id = new TwoDimensionalNGram[n_grams_by_unique_secondary_id_ll.size()];
		for (int i = 0; i < n_grams_by_unique_secondary_id.length; i++)
			n_grams_by_unique_secondary_id[i] = n_grams_by_unique_secondary_id_ll.get(i);
		
		// Prepare array for normalization
		double[] frequencies_by_unique_secondary_id_to_normalize = new double[n_grams_by_unique_secondary_id.length];
		for (int i = 0; i < frequencies_by_unique_secondary_id_to_normalize.length; i++)
			frequencies_by_unique_secondary_id_to_normalize[i] = secondary_string_id_to_frequency_map.get(n_grams_by_unique_secondary_id[i].getSecondaryStringIdentifier());
		
		frequencies_by_unique_secondary_id = mckay.utilities.staticlibraries.MathAndStatsMethods.normalize(frequencies_by_unique_secondary_id_to_normalize);
		
		// Update the values returned by secondary_string_id_to_frequency_map to the normalized frequencies
		for (int i = 0; i < n_grams_by_unique_secondary_id.length; i++)
		{
			String secondary_string_id = n_grams_by_unique_secondary_id[i].getSecondaryStringIdentifier();
			secondary_string_id_to_frequency_map.remove(secondary_string_id);
			secondary_string_id_to_frequency_map.put(secondary_string_id, frequencies_by_unique_secondary_id[i]);
		}
		
		n_grams_by_unique_joint_id = new TwoDimensionalNGram[n_grams_by_unique_joint_id_ll.size()];
		for (int i = 0; i < n_grams_by_unique_joint_id.length; i++)
			n_grams_by_unique_joint_id[i] = n_grams_by_unique_joint_id_ll.get(i);
		
		// Prepare array for normalization
		double[] frequencies_by_unique_joint_id_to_normalize = new double[n_grams_by_unique_joint_id.length];
		for (int i = 0; i < frequencies_by_unique_joint_id_to_normalize.length; i++)
			frequencies_by_unique_joint_id_to_normalize[i] = joint_string_id_to_frequency_map.get(n_grams_by_unique_joint_id[i].getJointStringIdentifier());
		
		frequencies_by_unique_joint_id = mckay.utilities.staticlibraries.MathAndStatsMethods.normalize(frequencies_by_unique_joint_id_to_normalize);
		
		// Update the values returned by joint_string_id_to_frequency_map to the normalized frequencies
		for (int i = 0; i < n_grams_by_unique_joint_id.length; i++)
		{
			String joint_string_id = n_grams_by_unique_joint_id[i].getJointStringIdentifier();
			joint_string_id_to_frequency_map.remove(joint_string_id);
			joint_string_id_to_frequency_map.put(joint_string_id, frequencies_by_unique_joint_id[i]);
		}
	}

	
	/* PUBLIC METHODS ***************************************************************************************/
	
	
	/**
	 * Returns the normalized frequency at which the n-gram having the given secondary identifier occurs among
	 * n-grams having a unique secondary identifier.
	 * 
	 * @param	secondary_id	The secondary identifier of the n-gram.
	 * @return					The frequency of the n-gram with the given secondary identifier.
	 */
	public double getFrequencyOfSecondaryIdentifier(LinkedList<double[]> secondary_id)
	{
		double frequency;
		String s = NGram.identifierToString(secondary_id);
		
		if (secondary_string_id_to_frequency_map.get(s) != null)
			frequency = secondary_string_id_to_frequency_map.get(s);
		else
			frequency = 0.0;
		
		return frequency;
	}
	
	
	/**
	 * Return the most common secondary identifier in this object's list of n-grams having a unique secondary 
	 * identifier. Note that the returned value may not be the secondary identifier of the n-gram having a 
	 * unique primary identifier that occurs the most frequently, nor that of the n-gram having a unique joint 
	 * identifier that occurs the most frequently.
	 * 
	 * @return	The secondary identifier of the n-gram that occurs the most frequently.
	 */
	public LinkedList<double[]> getMostCommonSecondaryIdentifier()
	{
		int index_of_highest_frequency = mckay.utilities.staticlibraries.MathAndStatsMethods.getIndexOfLargest(frequencies_by_unique_secondary_id);
		LinkedList<double[]> most_common_secondary_identifier = n_grams_by_unique_secondary_id[index_of_highest_frequency].getSecondaryIdentifier();
		
		return most_common_secondary_identifier;
	}
	
	
	/**
	 * Returns the normalized frequency at which the n-gram having the given primary and secondary identifiers 
	 * (together composing a joint identifier) occurs among n-grams having unique joint identifiers.
	 * 
	 * @param	primary_id		The primary identifier of the n-gram.
	 * @param	secondary_id	The secondary identifier of the n-gram.
	 * @return					The frequency of the n-gram with the given joint identifier.
	 */
	public double getFrequencyOfJointIdentifier(LinkedList<double[]> primary_id,
												LinkedList<double[]>  secondary_id)
	{
		double frequency;
		String s = TwoDimensionalNGram.jointIdentifierToString(primary_id, secondary_id);
		
		if (joint_string_id_to_frequency_map.get(s) != null)
			frequency = joint_string_id_to_frequency_map.get(s);
		else
			frequency = 0.0;
		
		return frequency;
	}
}
